# PIPELINE DEFINITION
# Name: launch-kubeflow-pytorchjob
# Description: An example to launch pytorch.
# Inputs:
#    delete_after_done: bool [Default: False]
#    job_timeout_minutes: int [Default: 600.0]
#    namespace: str [Default: 'mcliffor']
#    ttl_seconds_after_finished: int [Default: -1.0]
#    worker_replicas: int [Default: 1.0]
components:
  comp-name:
    executorLabel: exec-name
    inputDefinitions:
      parameters:
        active_deadline_seconds:
          isOptional: true
          parameterType: NUMBER_INTEGER
        backoff_limit:
          isOptional: true
          parameterType: NUMBER_INTEGER
        clean_pod_policy:
          defaultValue: Running
          isOptional: true
          parameterType: STRING
        delete_after_done:
          defaultValue: true
          isOptional: true
          parameterType: BOOLEAN
        job_timeout_minutes:
          defaultValue: 1440.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        master_spec:
          defaultValue: {}
          isOptional: true
          parameterType: STRUCT
        name:
          parameterType: STRING
        namespace:
          defaultValue: kubeflow
          isOptional: true
          parameterType: STRING
        ttl_seconds_after_finished:
          isOptional: true
          parameterType: NUMBER_INTEGER
        version:
          defaultValue: v1
          isOptional: true
          parameterType: STRING
        worker_spec:
          defaultValue: {}
          isOptional: true
          parameterType: STRUCT
deploymentSpec:
  executors:
    exec-name:
      container:
        args:
        - --name
        - '{{$.inputs.parameters[''name'']}}'
        - --namespace
        - '{{$.inputs.parameters[''namespace'']}}'
        - --version
        - '{{$.inputs.parameters[''version'']}}'
        - --masterSpec
        - '{{$.inputs.parameters[''master_spec'']}}'
        - --workerSpec
        - '{{$.inputs.parameters[''worker_spec'']}}'
        - --jobTimeoutMinutes
        - '{{$.inputs.parameters[''job_timeout_minutes'']}}'
        - --deleteAfterDone
        - '{{$.inputs.parameters[''delete_after_done'']}}'
        - --cleanPodPolicy
        - '{{$.inputs.parameters[''clean_pod_policy'']}}'
        - --activeDeadlineSeconds
        - '{{$.inputs.parameters[''active_deadline_seconds'']}}'
        - --backoffLimit
        - '{{$.inputs.parameters[''backoff_limit'']}}'
        - --ttlSecondsAfterFinished
        - '{{$.inputs.parameters[''ttl_seconds_after_finished'']}}'
        command:
        - python
        - /ml/launch_pytorchjob.py
        image: cascribner/kubeflow-pytorchjob-launcher:v1
pipelineInfo:
  description: An example to launch pytorch.
  name: launch-kubeflow-pytorchjob
root:
  dag:
    tasks:
      name:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-name
        inputs:
          parameters:
            active_deadline_seconds:
              runtimeValue:
                constant: 100.0
            backoff_limit:
              runtimeValue:
                constant: 1.0
            delete_after_done:
              componentInputParameter: delete_after_done
            job_timeout_minutes:
              componentInputParameter: job_timeout_minutes
            master_spec:
              runtimeValue:
                constant:
                  replicas: 1.0
                  restartPolicy: OnFailure
                  template:
                    metadata:
                      annotations:
                        sidecar.istio.io/inject: 'false'
                    spec:
                      containers:
                      - args:
                        - python3.11 -u run.py
                        command:
                        - /bin/bash
                        - -c
                        - --
                        image: quay.io/michaelclifford/test-train:0.0.11
                        name: pytorch
                        resources:
                          limits:
                            cpu: 2000m
                            memory: 8Gi
                            nvidia.com/gpu: 1.0
                          requests:
                            cpu: 2000m
                            memory: 8Gi
                            nvidia.com/gpu: 1.0
            name:
              runtimeValue:
                constant: pytorch-job
            namespace:
              componentInputParameter: namespace
            pipelinechannel--worker_replicas:
              componentInputParameter: worker_replicas
            ttl_seconds_after_finished:
              componentInputParameter: ttl_seconds_after_finished
            worker_spec:
              runtimeValue:
                constant:
                  replicas: '{{$.inputs.parameters[''pipelinechannel--worker_replicas'']}}'
                  restartPolicy: OnFailure
                  template:
                    metadata:
                      annotations:
                        sidecar.istio.io/inject: 'false'
                    spec:
                      containers:
                      - args:
                        - python3.11 -u run.py
                        command:
                        - /bin/bash
                        - -c
                        - --
                        image: quay.io/michaelclifford/test-train:0.0.11
                        name: pytorch
                        resources:
                          limits:
                            cpu: 2000m
                            memory: 8Gi
                            nvidia.com/gpu: 1.0
                          requests:
                            cpu: 2000m
                            memory: 8Gi
                            nvidia.com/gpu: 1.0
        taskInfo:
          name: name
  inputDefinitions:
    parameters:
      delete_after_done:
        defaultValue: false
        isOptional: true
        parameterType: BOOLEAN
      job_timeout_minutes:
        defaultValue: 600.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      namespace:
        defaultValue: mcliffor
        isOptional: true
        parameterType: STRING
      ttl_seconds_after_finished:
        defaultValue: -1.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      worker_replicas:
        defaultValue: 1.0
        isOptional: true
        parameterType: NUMBER_INTEGER
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
